language: ruby
rvm:
- 2.1.3
addons:
  code_climate:
    repo_token: 038d755d063226882ff2f6501f02e0591ae8dac97f41b2073465b6a9a3029b08

script: cd busslayer/ && bundle install && rake db:drop db:create db:migrate && bundle exec rake
