# define our source to look for gems
source "http://rubygems.org/"

# declare the sinatra dependency
gem "sinatra"

# database gems
gem "activerecord"
gem "sinatra-activerecord"
gem "pg"

#rake for tasks
gem "rake"

#others
gem 'annotate', '~> 2.6.5'
gem 'bcrypt'