ENV['RACK_ENV'] == 'test'

require "sinatra/activerecord/rake"


namespace :db do
  ENV['DB'] = true.to_s
  task :load_config do
    require "./app"
  end
end

require 'rspec/core/rake_task'
 
RSpec::Core::RakeTask.new :specs do |task|
  ENV['TESTING'] = true.to_s
  require "./app"
  task.pattern = Dir['spec/**/*.rb']
end
 
task :default => ['specs']
