ENV['RACK_ENV'] == 'test'

require "sinatra/activerecord/rake"
require "./app"

namespace :db do
  task :load_config do
    require "./app"
  end
end

require 'rspec/core/rake_task'
 
RSpec::Core::RakeTask.new :specs do |task|
  task.pattern = Dir['spec/**/*.rb']
end
 
task :default => ['specs']
